
package com.cachirulop.whereiparked.common.exception;

public class MapsForgeException
        extends Exception
{
    /**
     * Default serialVersionUID generated by the compiler
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constructs a new object with the message received as parameter
     * 
     * @param msg
     *            Error message of the exception
     */
    public MapsForgeException (String msg)
    {
        super (msg);
    }
}
